openapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
  description: API for managing documents in the order application.
servers:
  - url: http://localhost:3000/
    description: Development server
components: {}
